# Generated by Django 4.0.4 on 2022-05-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_students_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('school', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teacher_photo')),
            ],
        ),
    ]
